services:
  nginx:
    build: 
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - .:/var/www
      - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
      - 9000:8080
    networks:
      - app-network
    depends_on:
      - php
      - php_test
      
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/var/www
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - app-network
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: docker/mariadb/Dockerfile
    env_file:
      - .env
    environment:
      MARIADB_DATABASE: "$DB_DATABASE"
      MARIADB_USER: "$DB_USERNAME"
      MARIADB_PASSWORD: "$DB_PASSWORD"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    ports:
      - 3307:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  selenium:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - 4444:4444
      - 5900:5900
    networks:
      - app-network

  php_test:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - app-network
    depends_on:
      - db
      - selenium
    environment:
      APP_ENV: testing
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: problem_test
      DB_USERNAME: root
      DB_PASSWORD: ""

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
